[package]
name = "parity_rs"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
rand = "0.8"

[dependencies.utils]
path = "../../../common/rust"